myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path


from .views import (
    get_cookie_view,
    set_cookie_view,
    get_session_view,
    set_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    UsersList,
    UserDetailsView,
    UserUpdateView,
    HelloView,
)

app_name = "myauth"
urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"
    ),
    path("hello/", HelloView.as_view(), name="hello"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/", UsersList.as_view(), name="users-list"),
    path("about-me/<int:pk>/", UserDetailsView.as_view(), name="user_detail"),
    path("about-me/<int:pk>/update", UserUpdateView.as_view(), name="user_update"),

    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),

    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),

    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from blogapp.sitemaps import sitemaps


urlpatterns = [
    path('admin/doc', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    )
]

urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def avatar_dir(instance: "AvatarImage", filename: str) -> str:
    return "profiles/profile_{pk}/avatar/{filename}".format(
        pk=instance.pk,
        filename=filename
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_dir)

myauth/views.py
from random import random

from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView, LoginView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView
from django.utils.translation import gettext_lazy as _, ngettext
from django.views.decorators.cache import cache_page

from .models import Profile


class HelloView(View):
    welcome_message = _("welcome hello world")

    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get("items") or 0
        items = int(items_str)
        products_line = ngettext(
            "one product",
            "{count} products",
            items
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"
        )


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")


class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"


class UsersList(ListView):
    template_name = "myauth/users-list.html"
    context_object_name = "profiles"
    queryset = Profile.objects.all()


class UserDetailsView(DetailView):
    template_name = "myauth/about-me.html"
    model = User
    context_object_name = "user"


class UserUpdateView(UserPassesTestMixin, UpdateView):
    model = Profile
    fields = ("avatar",)

    def test_func(self):
        return self.request.user.is_staff or self.request.user.pk == self.get_object().user_id

    def get_success_url(self):
        return reverse(
            "myauth:user_detail",
            kwargs={"pk": self.object.user.pk},
        )


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


@cache_page(60 * 2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default_value")
    return HttpResponse(f"Cookie value: {value!r} + {random()}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        if request.user.is_authenicated:
            return redirect('/admin/')

        return render(request, 'myauth/login.html')

    username = request.POST["username"]
    password = request.POST["password"]

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect("/admin/")

    return render(request, "myauth/login.html", {"error": "invalid login credentials"})


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})

myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load cache %}

{% block title %}
  About me
{% endblock %}

{% block body %}
  <h1>User info</h1>
  <div>
      Products available: {% now "u" %}
  </div>
  {% if user.is_authenticated %}
    {% cache 300 userinfo user.username %}

      {% if user.profile.avatar%}
        <img src="{{ user.profile.avatar.url}}" alt="{{user.profile.avatar.name}}">
      {% else %}
        No avatar yet
      {% endif %}

      {% if request.user.is_staff or request.user.pk == user.pk %}
        <a href="{% url 'myauth:user_update' pk=user.profile.pk %}"
        ><h3>Update avatar</h3></a>
      {% endif %}

      <h2>Detail</h2>
      <p>Username: {{ user.username }}</p>
      <p>First name: {{ user.first_name }}</p>
      <p>Last name: {{ user.last_name }}</p>
      <p>Email: {{ user.email }}</p>
      <p>Bio: {{ user.profile.bio }}</p>
    {% endcache %}
  {% else %}
    <h2>User is anonymous</h2>
  {% endif %}
{% endblock %}

myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <title>
      {% block title %}
        Base Title
      {% endblock title %}
    </title>
    <style>
        * {
        font-family: 'Roboto', sans-serif;
           }
    </style>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

<div>
  {% now 'H:i' %}
</div>
<div>
  {% now 'l' as current_weekday %}
  Today is {{ current_weekday }}
</div>
</body>
</html>

myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
  Login
{% endblock %}

{% block body %}
  <div>
    <form method="post">
      {% csrf_token %}

      {{ form.as_p }}
      
      <button type="submit">Login</button>
    </form>
  </div>

{% endblock %}

myauth/templates/myauth/profile_form.html
{% extends 'myauth/base.html' %}

{% block title %}
  Update avatar
{% endblock %}

{% block body %}
  <h1>Update avatar</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update</button>
    </form>
  </div>
{% endblock %}

myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
  Register
{% endblock %}

{% block body %}
  <h1>Register</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
  </form>
{% endblock %}

myauth/templates/myauth/users-list.html
{% extends 'myauth/base.html' %}

{% block title %}
  Users list
{% endblock %}

{% block body %}
    <h1>Users:</h1>
    <div>
        {% for profile in profiles %}
            <p><a href="{% url 'myauth:user_detail' pk=profile.user.pk %}"
                ><h3>{{ profile.user.username }}</h3></a></p>
    {% endfor %}
    </div>
{% endblock  %}