myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path


from .views import (
    get_cookie_view,
    set_cookie_view,
    get_session_view,
    set_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    UsersList,
    UserDetailsView,
    UserUpdateView,
    HelloView,
)

app_name = "myauth"
urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"
    ),
    path("hello/", HelloView.as_view(), name="hello"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/", UsersList.as_view(), name="users-list"),
    path("about-me/<int:pk>/", UserDetailsView.as_view(), name="user_detail"),
    path("about-me/<int:pk>/update", UserUpdateView.as_view(), name="user_update"),

    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),

    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),

    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from blogapp.sitemaps import sitemaps


urlpatterns = [
    path('admin/doc', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    )
]

urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

shopapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter

from .views import (GroupsListView,
                    ProductsListView,
                    OrdersListView,
                    OrderCreateView,
                    ShopIndexView,
                    ProductDetailsView,
                    OrderDetailView,
                    ProductCreateView,
                    ProductUpdateView,
                    ProductDeleteView,
                    OrderUpdateView,
                    OrderDeleteView,
                    ProductsDataExportView,
                    OrderExportView,
                    ProductViewSet,
                    OrderViewSet,
                    LatestProductsFeed,
                    UserOrdersListView,
                    UserOrdersExportView,
                    )

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    # path("", cache_page(60 * 3)(ShopIndexView.as_view()), name="index"),
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("groups/", GroupsListView.as_view(), name="groups_list"),

    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user_orders"),
    path("users/<int:user_id>/orders/export/", UserOrdersExportView.as_view(), name="user_orders_export"),

    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/export/", OrderExportView.as_view(), name="orders-export"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/confirm-delete/", OrderDeleteView.as_view(), name="order_delete"),

    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="products_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"),

    path("products/latest/feed/", LatestProductsFeed(), name="products-feed"),
]

shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _, ngettext


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """
    Модель Product представляет товар, который можно продавать в интернет-магазине.

    Заказы тут: :model:`shopapp.Order`
    """
    class Meta:
        ordering = ["name", "price"]
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    # @property
    # def description_short(self) -> str:
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + "..."

    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r})"

    def get_absolute_url(self):
        return reverse("shopapp:products_list")


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to='orders/receipts/')

shopapp/forms.py
from django import forms
from django.contrib.auth.models import Group
from django.forms import ModelForm

from .models import Product, Order


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview"

    images = forms.ImageField(
        # widget=forms.ClearableFileInput(attrs={"multiple": True})
        # Максим Семенюк
        # Куратор
        # 21 сентября, 2023 21:32
        # Откатите версию джанго до 4.2.2, либо не используйте
        # widget=forms.ClearableFileInput(attrs={"multiple": True})
        # так как джанго не поддерживает из коробки загрузку нескольких файлов из одной формы.
    )


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "delivery_address", "promocode", "user", "products"
        widgets = {"products": forms.CheckboxSelectMultiple,
                   "delivery_address": forms.Textarea(attrs={"cols": 35, "rows": 5})
                   }


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ["name"]


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

shopapp/templates/shopapp/Order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm delete {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to delete {{ object.name }}</h1>
  <div>
    <form method="post">
      {% csrf_token %}

      {{ form.as_p }}

      <button type="submit">
        Delete
      </button>
    </form>
  </div>

  <div>
    <a href="{% url 'shopapp:order_details' pk=object.pk %}">
    >Back to order
    </a>
  </div>
{% endblock %}

shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <title>
      {% block title %}
        Base Title
      {% endblock title %}
    </title>
    <style>
        * {
        font-family: 'Roboto', sans-serif;
           }
    </style>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

<div>
  {% now 'H:i' %}
</div>
<div>
  {% now 'l' as current_weekday %}
  Today is {{ current_weekday }}
</div>
</body>
</html>

shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Groups List
{% endblock %}

{% block body %}
  <hl>Groups:</hl>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
  {% if not groups %}
    <h3>No groups yet</h3>
  {% else %}
    <ul>
      {% for group in groups %}
        <li>
          <div>{{ group.name }}</div>
          <ul>
            {% for permission in group.permissions.all %}
              <li>
                {{ permission.name }}
                (<code>{{ permission.codename }}</code>)
              </li>
            {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
  </div>
{% endblock %}

shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order #{{ object.pk }} details
{% endblock %}

{% block body %}
  <h1>Order #{{ object.pk }}</h1>
  <div>
    <p>0rder by {% firstof object.user.first_name object.user.username %}</p>
    <p>Promocode: <code>{{ object.promocode }}</code></p>
    <p>Delivery address: {{ object.delivery_address }}</p>
    <div>
      Product in order:
      <ul>
        {% for product in object.products.all %}
        <li>{{ product.name }} for	${{ product.price }}</li>
      {% endfor %}
      </ul>
    </div>
  </div>

  <div>
    <div>
    <a href="{% url 'shopapp:order_delete' pk=order.pk %}">
      >Delete order</a>
    </div>
    <div>
      <a href="{% url 'shopapp:order_update' pk=order.pk %}">
      >Update order</a>
    </div>
    <div>
      <a href="{% url 'shopapp:orders_list' %}">
      >Back to orders</a>
    </div>
  </div>
{% endblock %}

shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create order
{% endblock %}

{% block body %}
  <h1>Create a new order</h1>
  <div>
    <form method="post">
      {% csrf_token %}

      {{ form.as_p }}

      <button type="submit">
        Create
      </button>
    </form>
  </div>

  <div>
    <a href="{% url 'shopapp:orders_list' %}">
    >Back to Orders list
    </a>
  </div>
{% endblock %}

shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if object_list %}
    <div>
    {% for order in object_list %}
      <div>
        <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
        >Details #{{ order.pk }}</a></p>
        <p>0rder by {% firstof order.user.first_name order.user.username %}</p>
        <p>Promocode: <code>{{ order.promocode }}</code></p>
        <p>Delivery address: {{ order.delivery_address }}</p>
        <div>
          Product in order:
          <ul>
            {% for product in order.products.all %}
            <li>{{ product.name }} for	${{ product.price }}</li>
          {% endfor %}

          </ul>
        </div>
      </div>
    {% endfor %}
    </div>
  {% else %}
    <h3>No orders yet</h3>
  {% endif %}

  <div>
    <a href="{% url 'shopapp:order_create' %}">
    >Create new order
    </a>
  </div>
{% endblock %}

shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update order
{% endblock %}

{% block body %}
  <h1>Update order</h1>
  <div>
    <form method="post">
      {% csrf_token %}

      {{ form.as_p }}

      <button type="submit">
        Update
      </button>
    </form>
  </div>

  <div>
    <a href="{% url 'shopapp:order_details' pk=object.pk %}">
    >Back to order #{{ object.pk }}
    </a>
  </div>
{% endblock %}

shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
  <li>
      <a href="{% url 'admin:import_orders_csv' %}" class="addlink">
          Import CSV
      </a>
  </li>
  {{ block.super }}
{% endblock %}

shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm archived {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to archived {{ object.name }}</h1>
  <div>
    <form method="post">
      {% csrf_token %}

      {{ form.as_p }}

      <button type="submit">
        archived
      </button>
    </form>
  </div>

  <div>
    <a href="{% url 'shopapp:products_details' pk=object.pk %}">
    >Back to order
    </a>
  </div>
{% endblock %}

shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create a new product</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      {{ form.as_p }}

      <button type="submit">
        Create
      </button>
    </form>
  </div>

  <div>
    <a href="{% url 'shopapp:products_list' %}">
    >Back to products list
    </a>
  </div>
{% endblock %}

shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update product
{% endblock %}

{% block body %}
  <h1>Update product</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      {{ form.as_p }}

      <button type="submit">
        Update
      </button>
    </form>
  </div>

  <div>
    <a href="{% url 'shopapp:products_details' pk=object.pk %}">
    >Back to product #{{ object.pk }}
    </a>
  </div>
{% endblock %}

shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
  {% translate 'Products list' %}
{% endblock %}

{% block body %}
  <hl>{% translate 'Products' %}</hl>
  {% if products %}
    <div>
      {% blocktranslate count products_count=products|length %}
        There is only one product.
        {% plural %}
        There are {{ products_count }} products.
      {% endblocktranslate %}
    </div>
    <div>
    {% for product in products %}
      <div>
        <p><a href="{% url 'shopapp:products_details' pk=product.pk %}"
        >{% translate 'Name' context 'product name' %}: {{ product.name }}</a></p>
        <p>{% translate 'Price' %}: {{ product.price }}</p>
        {% translate 'no discount' as no_discount %}
        <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
        <p>{% translate 'Created by' %}: {{product.created_by}}</p>

        {% if product.preview %}
          <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}
      </div>
    {% endfor %}

    </div>

    {% if perms.shopapp.add_product %}
      <div>
        <a href="{% url 'shopapp:product_create' %}"
        >{% translate 'Create a new product' %}</a>
      </div>
    {% endif %}
  {% else %}
    {% url 'shopapp:product_create' as create_product_url %}
    {% blocktranslate %}
      <h3>No product yet</h3>
      <a href="{{ create_product_url }}"
      >Create a new one</a>
    {% endblocktranslate %}
  {% endif %}

{% endblock %}

shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
  Shop Index
{% endblock %}


{% block body %}
<h1>Hello Shop Index!</h1>

<div>
  <ul>
    {% for name, price in products %}
      <li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
      {% if name|length_is:'7' %}
        <span>Lucky product!</span>
      {% endif %}
    {% empty %}
      No products here
    {% endfor %}

  </ul>
</div>

<div>
<strong>
  You have {{ items }} cherr{{ items|pluralize:"y, ies" }}
</strong>
</div>

<div>
  Time running: {{ time_running }}
</div>

{% cache 100 lorem %}
<div>
  {% lorem 3 p random  %}
</div>
{% endcache %}

<div>
  <ul>
    {% for name, num in numbers %}
      <li>{{ name }} is {{ num }}</li>
      <span>{{ name|last }}</span>
    {% endfor %}
  </ul>
</div>

<div>
  <ul>
    {% for name, word in text %}
      <li>{{ name }} is {{ word }}</li>
      <span>{{ name|lower }}</span>
    {% endfor %}
  </ul>
</div>

{% endblock %}

shopapp/templates/shopapp/user-orders.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
User orders
{% endblock %}

{% block body %}
    {% if user_orders %}
        <h1>{{ owner.username }} created orders:</h1>
        <h2>Number of orders user: {{ user_orders|length }}</h2>
        {% cache 300 user-orders user.user_id %}
            {% for order in user_orders %}
                    <li><p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Order #{{ order.pk }}</a></p></li>
            {% endfor %}
        {% endcache %}
    {% else %}
        <h1>User {{ owner.username }} has not created orders yet</h1>
    {% endif %}
{% endblock %}